mysite/myapp/urls.py
from django.urls import path

from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('auth', views.auth, name='auth')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('myapp/', include("myapp.urls")),
    path('admin/', admin.site.urls),
]

mysite/myapp/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib import admin

# Create your models here.
class Question(models.Model):

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')   # Argumento opcional com um nome legível

    def __str__(self):
        return self.question_text
    
    @admin.display(
        boolean  = True,
        ordering = 'pub_date',
        description = 'Was Published Recently? ',
    )
    
    def was_published_recently(self):
        now = timezone.now()
        return now - timezone.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/myapp/views.py
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.contrib.auth import authenticate

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'myapp/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'myapp/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'myapp/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'myapp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('myapp:results', args=(question.id,)))
    
# Autenticando
def auth(request):
    user = authenticate(username="John", password='123456')

    if user is not None:
        context = {
            'user': user
        }
    
    else:
        raise Http404("User not found! You're logged in as an annonymous user ")
    
    return render(request, 'myapp/auth.html', context)

mysite/myapp/templates/myapp/admin/base_site.html
{% extends "admin/base.html" %}

{% block title %}{% if subtitle %}{{ subtitle }} | {% endif %}{{ title }} | {{ site_title|default:_('mysite admin') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">myapp Administration</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}

mysite/myapp/templates/myapp/auth.html
<h1>Welcome {{ user }}</h1>

<p>You're now logged in! </p>

mysite/myapp/templates/myapp/detail.html
<form action="{% url 'myapp:vote' question.id %}" method="post">
   {% csrf_token %}
   <fieldset>
       <legend><h1>{{ question.question_text }}</h1></legend>
       {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
       {% for choice in question.choice_set.all %}
           <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
           <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
       {% endfor %}
   </fieldset>
   <input type="submit" value="Vote">
   </form>

mysite/myapp/templates/myapp/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'myapp/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/myapp/{{ question.id }}/">{{ question.question_text }}</a></li>
        <!-- Dá para fazer assim também
        <li><a href="/myapp/{% url 'myapp:detail' question.id %}" /></li>
        -->
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/myapp/templates/myapp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_set }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'myapp:detail' question.id %}">Vote again?</a>